    -- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS ifbank;

-- Selecionar o banco de dados
USE ifbank;

-- Tabela de CLIENTES
CREATE TABLE CLIENTES (
    CPF VARCHAR(11),
    NOME_COMPLETO VARCHAR(80) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF)
);

-- Tabela de CONTAS
CREATE TABLE CONTAS (
    NUMERO BIGINT,
    TIPO VARCHAR(45) NOT NULL,
    SALDO DECIMAL(10, 2) NOT NULL,
    STATUS TINYINT NOT NULL,
    CPF_CLIENTE VARCHAR(11),
    CONSTRAINT PK_CONTA PRIMARY KEY (NUMERO_CONTA),
    CONSTRAINT FK_CLIENTE_CONTA FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTES(CPF)
);

-- Tabela de REGISTRO_TRANSACOES
CREATE TABLE REGISTRO_TRANSACOES (
    NUMERO_TRANSACAO INT,
    NUMERO_CONTA_ORIGEM BIGINT NOT NULL,
    NUMERO_CONTA_DESTINO BIGINT NOT NULL,
    DATA_TRANSACAO DATE NOT NULL,
    VALOR_TRANSACAO DECIMAL(10, 2) NOT NULL,
    TIPO_TRANSACAO enum('CREDITO', 'DEBITO', 'TRANSACAO_CREDITO', 'TRANSACAO_DEBITO'),
    CONSTRAINT PK_TRANSACAO PRIMARY KEY (NUMERO_TRANSACAO)
);

-- Tabela de RELACIONAMENTO entre CONTAS e REGISTRO_TRANSACOES
CREATE TABLE CONTAS_TRANSACOES (
    NUMERO_CONTA BIGINT,
    NUMERO_TRANSACAO INT,
    CONSTRAINT PK_CONTAS_TRANSACOES PRIMARY KEY (NUMERO_CONTA, NUMERO_TRANSACAO),
    CONSTRAINT FK_CONTA_TRANSACAO FOREIGN KEY (NUMERO_CONTA) REFERENCES CONTAS(NUMERO_CONTA),
    CONSTRAINT FK_TRANSACAO_CONTA FOREIGN KEY (NUMERO_TRANSACAO) REFERENCES REGISTRO_TRANSACOES(NUMERO_TRANSACAO)
);
